// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ-fEwgR1XX4QE7Mv37mMvQKuW7Dgek0Y',
    appId: '1:793080128652:web:49d999492c5714c48b47a9',
    messagingSenderId: '793080128652',
    projectId: 'explorelab-29cb5',
    authDomain: 'explorelab-29cb5.firebaseapp.com',
    storageBucket: 'explorelab-29cb5.firebasestorage.app',
    measurementId: 'G-X5B82NP333',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03Xqz9N-nTI1IKrcS1yNmPz1dVaL9hiU',
    appId: '1:793080128652:android:c046a8c3242a8eec8b47a9',
    messagingSenderId: '793080128652',
    projectId: 'explorelab-29cb5',
    storageBucket: 'explorelab-29cb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3bP6nIQcfWlkbJZN81io0Xuw2h7JTPAk',
    appId: '1:793080128652:ios:ff22ec37a00d3c678b47a9',
    messagingSenderId: '793080128652',
    projectId: 'explorelab-29cb5',
    storageBucket: 'explorelab-29cb5.firebasestorage.app',
    iosBundleId: 'com.explorelab.explorelab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3bP6nIQcfWlkbJZN81io0Xuw2h7JTPAk',
    appId: '1:793080128652:ios:ff22ec37a00d3c678b47a9',
    messagingSenderId: '793080128652',
    projectId: 'explorelab-29cb5',
    storageBucket: 'explorelab-29cb5.firebasestorage.app',
    iosBundleId: 'com.explorelab.explorelab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ-fEwgR1XX4QE7Mv37mMvQKuW7Dgek0Y',
    appId: '1:793080128652:web:5ad36342821141d18b47a9',
    messagingSenderId: '793080128652',
    projectId: 'explorelab-29cb5',
    authDomain: 'explorelab-29cb5.firebaseapp.com',
    storageBucket: 'explorelab-29cb5.firebasestorage.app',
    measurementId: 'G-MGWDH6TB99',
  );
}
